### PR TITLE
Schema registry 7.3.1 & use BBC registry

### PR DESCRIPTION
**Pull request by OuesFa**
https://blablacar.atlassian.net/browse/DBRE-3305

### CODE REVIEW

**Review by frivoire — APPROVED** [review]
👍 

Do you plan to do a release of the chart at the same time ?

**Comment by OuesFa** [comment]
@frivoire I don't know, maybe push the 7.2.2 to the registry and leave the current version, wdyt?

**Comment by frivoire** [comment]
This PR is a chart, not dockerfiles, so it's not about pushing to registry.
My remark was more : "you probably should change the chart version to make a release, and not require another PR just afterwards"

**Comment by OuesFa** [comment]
>This PR is a chart, not dockerfiles, so it's not about pushing to registry.
I know. Let me clarify - currently, the 7.2.2 version is not available in our registry. If we want to avoid creating a new version of the chart, the simpler solution would be for me to push the 7.2.2 version through the dockerfiles repository and just change the repository here.

**Pull request merged**
