### PR TITLE
[DBRE-2970][schema-registry] use dedicated datastores nodepool

### PR DESCRIPTION
**Pull request by aymeric-ledizes**

### CODE REVIEW

**Review by mfouilleul — APPROVED** [review]

**Comment by mfouilleul** [comment]
I don't know if in the context of a fork it is good to set the value here or directly in the HR?

**Comment by OuesFa** [comment]
> I don't know if in the context of a fork it is good to set the value here or directly in the HR?

It would be a bit tedious I think to duplicate the confs in every HR. 
I would say that the values file is not that hard to handle when managing conflicts with the upstream, so LGTM

**Comment by OuesFa** [comment]
An open question, do we also put our stateless apps (like this one) in the datastores nodepool?

**Comment by aymeric-ledizes** [comment]
> An open question, do we also put our stateless apps (like this one) in the datastores nodepool?

I would say yes same as proxysql as schema registry is a critical component

**Comment by frivoire** [comment]
I also think it's a good thing to put stateless apps in the datastores nodepool, because they are managed by us (we monitor their cpu usage) and their latency is important too. The fact that they are stateless is not really important here I think.

**Review by frivoire — APPROVED** [review]

**Pull request merged**
